import {Navbar} from "../components/Navbar";

export default function About() {
    return (
        <>
            <Navbar/>
            <div className='m-10 flex flex-col items-center dark:prose-invert prose-lg lg:prose-xl m-auto'>
                <h1 className={`text-center font-bold`}>The Origin of LoveWorks</h1>
                <p>Every Sunday, for some years, Mimi Phillips has been cooking brunch at the Sonoran Desert Inn for our town. These weekly events bring Ajo tourists and locals together around communal tables. Returning annually, winter “snowbirds”—those who have second homes here, and those who are just in Ajo for the season—also enjoy homestyle cooking while engaging in conversation and camaraderie. Amazing connections and memories are borne of attending this event.</p>
                <p>In the fall of 2021, Averill Lovely of Brownville, Maine, came—along with his wife, baby and extended family—to Ajo. They wintered during COVID and decided to purchase a winter home here. Averill is an extremely talented and engaging professional musician who sings and plays the guitar. He loved the opportunity to share this time with his dad, Ralph Lovely, an exceptional banjo player. Others joined in: Beth Weber on the fiddle, Don Petersen on the bass cello, and Terry Siess, also on the banjo. They called themselves The Kitchen Table Band. Soon, all attendees at Sunday Brunch were gifted with their music. </p>
                <p>To be sure, some tips came their way from those listening, but most of the diners had little extra income, just a lot of music enthusiasm. Because Mimi only charges $10 a plate for brunch, she couldn’t afford to pay them to play this great music. So, by way of a “thank-you”, she suggested making a ticketed, tri-cultural dinner—at which the band would play—featuring the foods of our “Three Nations”. </p>
                <p><strong>The 1st Annual LoveWorks Food and Music Gathering</strong> was held out in the desert at Cow Pie Rock. (Don’t let the name fool you! It’s a beautiful setting along Ajo’s Scenic Loop.). Mimi felt this was another way in which to bring our community together for some good fun and good music, outdoors, safe from COVID. Mimi had camped out at the rock with friends in the past. It was always wonderful, and last year’s party at the Cow Pie was no exception! The Kitchen Table band played while 150 plus folks ate, and afterward a community jam was held around a bonfire. The proceeds of the donations for the tickets, minus expenses, went to the band. </p>
                <p>The food and music Gathering at Cow Pie Rock in March of 2022 was such a success and was so well received that Averill and Mimi started brainstorming how it could be expanded into a proper festival—over a three-day weekend—for a second year. This year a new guitar player will join the band, Tony Brown. And multiple events will follow the Friday night Cow Pie dinner.</p>
                <p>The term LoveWorks was something Averill adapted from an art exhibit in Istanbul by a good friend named John D'Agostino. They were fellow ex-pats in Istanbul and became good pals in the early 2000s. In 2005, John had eye surgery and afterward was able to see the world in a whole new way. His last art exhibit featured themes of new vision and the idea that love works night and day. In 2006, John died tragically in a train accident, and part of mourning the loss of this friend was to honor his ideas and spirit. So, out of that came <strong>LoveWorks Entertainment</strong>, the <strong>LoveWorks band</strong>, and now, the <strong>LoveWorks! Night and Day in Ajo desert festival</strong>. The idea is to promote peace, love and eccentricity in all its beautiful, artistic forms. Love Works resonates perfectly with Ajo. It is the most rural town in Pima county, where the three Nations: the Tohono O’odham Nation, Mexico and the United States intersect. For 20 years every September, all Three Nations celebrate International Day of Peace with a parade and a gathering in our Plaza. Borders and boundaries are transcended. LoveWorks here in Ajo, and it can work everywhere.</p>
            </div>
        </>

    );
}