import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
// @ts-ignore
import {Navbar} from '@/components/Navbar'
// @ts-ignore
import {Hero} from '@/components/home/Hero'

// @ts-ignore
import {Events} from '@/components/home/Events/Events'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
    <div className='dark:bg-gray-800 bg-white'>
            <Hero  />
            <Events />
    </div>
    </>
  )
}
